version: 0.2

env:
  variables:
    DOCKER_REGISTRY_USERNAME: your-docker-username
    DOCKER_REGISTRY_PASSWORD: your-docker-password
    DOCKER_REGISTRY_URL: your-docker-registry-url

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing AWS CLI..."
      - pip install awscli
      - echo "Installing Docker..."
      - curl -fsSL https://get.docker.com | sh
      - echo "Docker version:"
      - docker --version
  pre_build:
    commands:
      - echo "Logging in to Docker registry..."
      - echo $DOCKER_REGISTRY_PASSWORD | docker login -u $DOCKER_REGISTRY_USERNAME --password-stdin $DOCKER_REGISTRY_URL
  build:
    commands:
      - echo "Building Docker image..."
      - cd path/to/your/flask-app
      - docker build -t $DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/simple-python-flask-app:latest .
  post_build:
    commands:
      - echo "Pushing Docker image to the registry..."
      - docker push $DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/simple-python-flask-app:latest
artifacts:
  files:
    - '**/*'
  base-directory: path/to/your/flask-app


